spring.application.name=WishlistManagerApplication

spring.dataSource.url=jdbc:postgresql://localhost:5432/Wishlist Manager

spring.security.user.name=devanshu
spring.security.user.password=0321

spring.dataSource.username=postgres
spring.dataSource.password=devanshu
