name: Scheduled Ping

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ping_url:
    runs-on: ubuntu-latest
    steps:
    - name: Ping URL
      uses: sisodiya2421/pinger@master
      env:
        URL: ${{ secrets.URL }}
